name: on-tag-release-npm

on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    publish-into-npm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup node version
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Remove Husky on prepare
              run: npm pkg delete scripts.prepare
            - name: Installing project dependencies
              run: npm install
            - name: Publishing to NPM
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: 'public'
