name: release-npm-on-tag

on:
    push:
        # Sequence of patterns matched against refs/tags
        tags:
            - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish-into-npm:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          with:
            node-version: "16"
        - run: npm set-script prepare ""
        - run: npm install
        - uses: JS-DevTools/npm-publish@v1
          with:
            token: ${{ secrets.NPM_TOKEN }}
            access: 'public'
